### Задание 1.

In [1]:
import numpy as np

In [35]:
N = 15

In [36]:
M = np.arange(N, -1, -1)

In [37]:
M

array([15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

### Задание 2. 

In [31]:
M1 = M.reshape(4, 4)

In [38]:
M1

array([[15, 14, 13, 12],
       [11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])

In [39]:
print(sum(np.diagonal(M1)))

30


### Задание 3.

In [42]:
k = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )

In [43]:
s = np.array( [4, 12, -3] )

In [44]:
from numpy import linalg

In [45]:
linalg.solve(k, s)

array([ 0.46666667,  3.84444444, -5.55555556])

### Задание 4.

In [46]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [49]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [52]:
a = next_user_stats 
b = users_stats

In [56]:
aL = np.linalg.norm( a )

In [58]:
users = []

In [69]:
for i in b:
    bL = np.linalg.norm( i )
    users.append(np.dot( a, i ) / ( aL * bL ))
    print(round(np.dot( a, i ) / ( aL * bL ), 4))
print('Максимальное сходство:', round(max(users), 4))

0.2
0.8452
0.4
0.7906
0.4
0.0
0.0
0.9487
0.0
0.0
Максимальное сходство: 0.9487
